on:
  push:
    branches: [ main ]

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Dependencies
      run: npm install      
    
# Adds variables to the environment    
    - name: Add Email Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_EMAIL'
        value: ${{ secrets.SOCIAL_EMAIL }}
    - name: Add YouTube Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_YOUTUBE'
        value: ${{ secrets.SOCIAL_YOUTUBE }}
    - name: Add LinkedIn Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_LINKEDIN'
        value: ${{ secrets.SOCIAL_LINKEDIN }}
    - name: Add Steam Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_STEAM'
        value: ${{ secrets.SOCIAL_STEAM }}
    - name: Add Discord Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_DISCORD'
        value: ${{ secrets.SOCIAL_DISCORD }}
    - name: Add GitHub Link
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'SOCIAL_GITHUB'
        value: ${{ secrets.SOCIAL_GITHUB }}
    
    - name: AddDateTime
      uses: 1466587594/get-current-time@v2.0.0
      id: current-time
      with:
        utcOffset: "+11:00"
    - name: Add Publish Date
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'PUBLISH_DATE'
        value: ${{ steps.current-time.outputs.readableTime }}
    - name: Add Repo Path
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'REPO_PATH'
        value: https://github.com/${{ github.repository }}
    - name: Add VersionInfo
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'VERSION_INFO'
        value: ${{ github.event.head_commit.message }}
    - name: Add GitHub LinkBack
      uses: TickX/var-to-dotenv@v1.1.4
      with:
        key: 'COMMIT_SHA'
        value: ${{ github.sha }}
        
    - name: Build Project
      run: npm run generate
      
    - name: Check file existence
      id: check_folder
      uses: andstor/file-existence-action@v1
      with:
        allow_failure: true
        files: "${{ github.workspace }}/dist"
        
    - name: Clear Old Files  
      if: steps.check_folder.outputs.files_exists == 'true'
      uses: appleboy/ssh-action@master
      with:
        script: ${{ secrets.HOST_COMMAND }}
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASS }}
  
    - name: Copy build to server
      if: steps.check_folder.outputs.files_exists == 'true'
      uses: garygrossgarten/github-action-scp@release
      with:
        local: ${{ github.workspace }}/dist
        remote: ${{ secrets.BUILD_DIR }}
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASS }}
